2022-07-17 11:27:31,013:DEBUG:certbot._internal.main:certbot version: 1.29.0
2022-07-17 11:27:31,014:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2022-07-17 11:27:31,014:DEBUG:certbot._internal.main:Arguments: ['--webroot', '-w', '/acme-challenge', '-d', 'council-vote.42heilbronn.de', '-m', 'radelwar@student.42heilbronn.de', '--agree-tos', '--no-eff-email']
2022-07-17 11:27:31,014:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2022-07-17 11:27:31,034:DEBUG:certbot._internal.log:Root logging level set at 30
2022-07-17 11:27:31,035:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2022-07-17 11:27:31,038:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fb5de3a09d0>
Prep: True
2022-07-17 11:27:31,038:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fb5de3a09d0> and installer None
2022-07-17 11:27:31,038:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2022-07-17 11:27:31,047:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/635097156', new_authzr_uri=None, terms_of_service=None), f166c8e9901ea30a650bc2b8baa82a66, Meta(creation_dt=datetime.datetime(2022, 7, 17, 10, 58, 10, tzinfo=<UTC>), creation_host='bcb3ede194ce', register_to_eff=None))>
2022-07-17 11:27:31,047:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2022-07-17 11:27:31,049:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2022-07-17 11:27:31,535:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2022-07-17 11:27:31,540:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 17 Jul 2022 11:27:31 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "CmlxMsSuf9A": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2022-07-17 11:27:31,541:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for council-vote.42heilbronn.de
2022-07-17 11:27:31,925:DEBUG:certbot.crypto_util:Generating RSA key (2048 bits): /etc/letsencrypt/keys/0006_key-certbot.pem
2022-07-17 11:27:31,928:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0006_csr-certbot.pem
2022-07-17 11:27:31,929:DEBUG:acme.client:Requesting fresh nonce
2022-07-17 11:27:31,929:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2022-07-17 11:27:32,090:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2022-07-17 11:27:32,091:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 17 Jul 2022 11:27:32 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0101n7Z-7S9htyTXm4o8v4_Dw19mgOM-NFTRjbghnhx-lc4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2022-07-17 11:27:32,091:DEBUG:acme.client:Storing nonce: 0101n7Z-7S9htyTXm4o8v4_Dw19mgOM-NFTRjbghnhx-lc4
2022-07-17 11:27:32,091:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "council-vote.42heilbronn.de"\n    }\n  ]\n}'
2022-07-17 11:27:32,094:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNjM1MDk3MTU2IiwgIm5vbmNlIjogIjAxMDFuN1otN1M5aHR5VFhtNG84djRfRHcxOW1nT00tTkZUUmpiZ2huaHgtbGM0IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "p-k0io5YYDRn21fZFA5c1DhONhVb9fZVvEOkBR6uAzCEJ5F50VKqv55knRJ785idk3Njet7KwDdfxjs6qnvmD6hUDMqnK1P49b-wKGNemCN2mDQKTQzpZ4xEVO3PkeZsTI_SLwZgAbhLUNDGw04r81psrHeDItmURGTPK6jf6fNkf6NaTCd2QsKgOnEc6L-KHt039dFf4wglr04Is2tUnLi2f1AKB43jWufhHqaPNkkYmiSL6iH7B37cYXBp48R4lBWYV6TnmYSJ4UpqCqgtzV08kXOiwAIweK8KrU9y6VQLlWZG7Xu_EYIIArRZByImEtPqTGMPsoKEanTpvE9oCQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImNvdW5jaWwtdm90ZS40MmhlaWxicm9ubi5kZSIKICAgIH0KICBdCn0"
}
2022-07-17 11:27:32,309:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 213
2022-07-17 11:27:32,310:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Sun, 17 Jul 2022 11:27:32 GMT
Content-Type: application/problem+json
Content-Length: 213
Connection: keep-alive
Boulder-Requester: 635097156
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 01023eWVgAr0_4KBO28qUQGyWgWJWq0R0xoNHKjIj9__aPs

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/",
  "status": 429
}
2022-07-17 11:27:32,310:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1744, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1591, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 141, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 530, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 442, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 492, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 942, in new_order
    return cast(ClientV2, self.client).new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 703, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/opt/certbot/src/acme/acme/client.py", line 103, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 1275, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 1289, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 1135, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
2022-07-17 11:27:32,313:ERROR:certbot._internal.log:An unexpected error occurred:
2022-07-17 11:27:32,313:ERROR:certbot._internal.log:Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
